<?php
// Template name: Terms Page 
?>
<div class="pk-container">
    <div class="pk-subheader">
        <a class="legal">Legal</a>
    </div>
    <div class="pk-content">
        <div class="pk-title">
            <div>
                <h1 class="pk-main-title align-center">Perkfix.com Website Terms of use</h1>
            </div>
            <div>
                <h1 class="pk-main-desc align-center">Legal Information & Notices</h1>
            </div>
        </div>
        <hr/>
        <div class="pk-content-part">
            <h2>Ownership of Site; Agreement to Terms of Use</h2>
            <p>These Terms and Conditions of Use (the "Terms of Use") apply to the Perkfix web site located at www.Perkfix.com, and all associated sites linked to www.Perkfix.com by Perkfix, its subsidiaries and affiliates, including Perkfix sites around the world (collectively, the "Site"). The Site is the property of Perkfix Inc. ("Perkfix") and its licensors. BY USING THE SITE, YOU AGREE TO THESE TERMS OF USE; IF YOU DO NOT AGREE TO THESE TERMS OF USE, IMMEDIATELY STOP USING THE SITE AND DO NOT USE ANY PERKFIX SERVICE, PARTICIPATE IN ANY PERK PROGRAM OR PURCHASE ANY PRICING PACKAGE, PRODUCT OR OTHER GOOD[S] OR SERVICE OFFERED THROUGH THE SITE. <br/><br/>
            Perkfix reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these Terms of Use, Perkfix grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site. <br/><br/>
            By entering your email you agree to receive personalized Perkfix deals each day. You may unsubscribe at anytime. <br/>
            Welcome to the Perkfix Site (defined below). By using it, you are agreeing to these Terms of Use (defined below). Please read them carefully. If you have any questions, contact us here. <br/>
            These Terms of Use were last updated on November 1st, 2019. <br/>
            Perkfix, Inc. (“Perkfix” "we" or “us” or “our”) owns and operates the website, www.Perkfix.com, the mobile and touch versions and any sites we have now or in the future that reference these Terms of Use (collectively, "Site"). By using the Site and Perkfix’s services through the Site, you agree to these Terms of Use (defined below) and any additional terms applicable to certain programs in which you may elect to participate. You also agree to our Privacy Statement, located at http://www.Perkfix.com/privacy, and acknowledge that you will regularly visit the Terms of Use (defined below) to familiarize yourself with any updates. <br/>
            The Privacy Statement, together with these terms of use, and any other terms contained herein or incorporated herein by reference, are collectively referred to as the "Terms of Use." The term "using" also includes any person or entity that accesses or uses the Site with crawlers, robots, data mining or extraction tools or any other functionality.</p>

            <h2>About the Site</h2>
            <p>The Site is a platform through which we offer payment cards to be used on products within the Perkfix Store and up to the monthly allowance that is set by the company. <br/>
            You agree to the right of whomever you "Approve" to use Perkfix will have access to this allowance and be able to use their Perkfix cards with the funding source linked to your bank account. <br/><br/>
            Any amount that is spent by an employee of your company is non-refundable. Un-used allowances maybe refundable, or may be added back to employer’s balance depending on the contract between Perkfix and the employer. <br/>
            Any or all of the amount that is spent by a member of your company may have tax implications that your company and/or employees may be responsible for.</p>

            <h2>Your Use of the Site</h2>
            <p>As a condition of your use of the Site, you agree that: <br/>
            You have reached the age of majority in the state or province in which you reside; <br/>
            You are able to create a binding legal obligation; <br/>
            You are not barred from receiving products or services under applicable law; <br/>
            You will not attempt to use the Site with crawlers, robots, data mining or extraction tools or any other functionality; <br/>
            Your use of the Site will at all times comply with these Terms of Use; <br/>
            You will only make legitimate purchases that comply with the letter and spirit of the terms of the respective offers; <br/>
            You will have the right to use Perkfix as an employee perk, benefits, reward and incentive program - any other use cases may violate the terms of service and we have the right to revoke your service to the account; <br/>
            You have the right to provide any and all information you submit to the Site, and all such information is accurate, true, current and complete; <br/>
            You will update and correct information you have submitted to the Site and ensure that it is accurate at all times (out-of-date information will invalidate your account); and, <br/>
            You will only purchase a Partner Package, Product or participate in other available programs through the Site by creating an account on the Site, and any purchase will be subject to the applicable Terms of Sale set forth in these Terms of Use. <br/>
            You agree to the right of whomever you "Approve" to use Perkfix will have access to this allowance and be able to use their Perkfix cards with the funding source linked to your bank account. <br/><br/>

            Any amount that is spent by a member of your company is non-refundable. Only un-used allowances maybe refundable, or may be added back to employer’s balance depending on the contract between Perkfix and the employer. <br/><br/>
            
            Perkfix retains the right, at our sole discretion, to deny service or use of the Site or an account to anyone at any time and for any reason. While we use reasonable efforts to keep the Site and your account accessible, the Site and/or your account may be unavailable from time to time. You understand and agree that there may be interruptions in service or events, Site access or access to your account due to circumstances both within our control (e.g., routine maintenance) and outside of our control.</p>

            <h2>Your Access to the Site</h2>
            <p>Perkfix retains the right, at our sole discretion, to deny service or use of the Site or an account to anyone at any time and for any reason. While we use reasonable efforts to keep the Site and your account accessible, the Site and/or your account may be unavailable from time to time. You understand and agree that there may be interruptions in service or events, Site access or access to your account due to circumstances both within our control (e.g., routine maintenance) and outside of our control.</p>

            <h2>Modification</h2>
            <p>We reserve the right at all times to discontinue or modify any part of these Terms of Use in our sole discretion. If we make changes that affect your use of the Site or our services we will post notice of the change on the Terms of Use page. Any changes to these Terms of Use will be effective upon our posting of the notice; provided that these changes will not apply to Partner Packages or Products purchased prior to the effective date of such changes. If you do not agree to the changes, you may close your account and you should not use the Site or any services offered through the Site after the effective date of the changes. We suggest that you revisit our Terms of Use regularly to ensure that you stay informed of any changes. You agree that posting notice of any changes on the Terms of Use page is adequate notice to advise you of these changes, and that your continued use of the Site or our services will constitute acceptance of these changes and the Terms of Use as modified.</p>

            <h2>Your Account</h2>
            <p>You are responsible for updating and correcting information you have submitted to create or maintain your account. As part of your account settings, you have the option to save, edit or delete your personal information, including, without limitation, a valid credit card. You understand and agree that Perkfix shall have no responsibility for any incident arising out of, or related to, your account settings. You must safeguard your password and supervise the use of your account. You are solely responsible for maintaining the security of your account and maintaining settings that reflect your preferences. We will assume that anyone using the Site or transacting through your account is you. You agree that you are solely responsible for any activity that occurs under your account. <br/>
            The Site may permit you to make purchases without an account or without logging in to your account. If you make a purchase in this manner, we will create an account for you based on the information provided to us in connection with the transaction (e.g., your name, address, e-mail address, and other transaction information). <br/>
            Your account is non-transferrable. You cannot sell, combine, or otherwise share it with any other person. Any violation of these Terms of Use, including, without limitation, failure to maintain updated and correct information about your account (e.g., valid credit card information) will cause your account to fall out of good standing and we may cancel your account in our sole discretion. If your account is cancelled, you may forfeit any pending, current or future account credits, and any other forms of unredeemed value in your account. Upon termination, the provisions of these Terms of Use that are by their nature intended to survive termination (e.g., any disclaimers, all limitations of liability and all indemnities) shall survive. We also reserve the right to change or discontinue any aspect or feature of our services or the Site, including, without limitation, requirements for use. <br/>
            By creating an account, you grant Perkfix a non-exclusive, worldwide, perpetual, paid-up, irrevocable, royalty free license and right to use, publicly display, broadcast, and publish any company logos or names associated with the organization affiliated with the account. Affiliation is determined on the basis of account use. Namely, if the account is used to book a Package on behalf of the company.</p>

            <h2>Your Conduct</h2>
            <p>All interactions on the Site must comply with these Terms of Use. To the extent your conduct, in our sole discretion, restricts or inhibits any other user from using or enjoying any part of the Site, we may limit or terminate your privileges on the Site and seek other remedies, including, without limitation, cancellation of your account or forfeiture of any forms of unredeemed value in your account. <br/>
            The following activities are prohibited on the Site and constitute violations of these Terms of Use: <br/>
            Submitting any content to the Site that: <br/>
            Violates applicable laws (including, without limitation, but not limited to intellectual property laws, laws relating to rights of privacy and rights of publicity and laws related to defamation); <br/>
            Contains personal information, except when we expressly ask you to provide such information; <br/>
            Contains viruses or malware; <br/>
            Offers unauthorized downloads of any copyrighted, confidential or private information; <br/>
            Has the effect of impersonating others; <br/>
            Contains messages by non-spokesperson employees of Perkfix purporting to speak on behalf of Perkfix or provides confidential information concerning Perkfix; <br/>
            Contains chain letters of any kind; <br/>
            Is purposely inaccurate, commits fraud or falsifies information in connection with your Perkfix account or to create multiple Perkfix accounts; or Is protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right. <br/>
            Attempting to do or actually doing any of the following: <br/>
            Accessing data not intended for you, such as logging into a server or an account which you are not authorized to access; <br/>
            Scanning or monitoring the Site for data gathering purposes in an effort to track sales, usage, aggregate offering information, pricing information or similar data; <br/>
            Scanning or testing the security or configuration of the Site or breaching security or authentication measures; or <br/>
            Interfering with service to any user in any manner, including, without limitation, by means of submitting a virus to the Site or attempting to overload, “flood,” “spam,” “mail bomb” or “crash” the Site. <br/>
            Using any of the following: <br/>
            Frames, framing techniques or framing technology to enclose any content included on the Site without our express written permission; <br/>
            Any Site content, including without limitation User Content (defined below), in any meta tags or any other “hidden text” techniques or technologies without our express written permission; <br/>
            The Site or any of its contents to advertise or solicit, for any commercial, political or religious purpose or to compete, directly or indirectly, with Perkfix; or <br/>
            The Site or any of its resources to solicit consumers, Partners or other third-parties to become users or partners of other online or offline services directly or indirectly competitive or potentially competitive with Perkfix, including, without limitation, aggregating current or previously offered deals. Collecting any of the following: <br/>
            Content from the Site, including, without limitation, in connection with current or previously offered deals, and featuring such content to consumers in any manner that diverts traffic from the Site without our express written permission; or <br/>
            Personal Information (defined in our Privacy Statement), User Content (defined in Section 12 below) or content of any consumers or Partners. Engaging in any of the following: <br/>
            Tampering or interfering with the proper functioning of any part, page or area of the Site or any functions or services provided by Perkfix; <br/>
            Taking any action that places excessive demand on our services or imposes, or may impose, an unreasonable or disproportionately large load on our servers or other portion of our infrastructure (as determined in our sole discretion); <br/>
            Reselling or repurposing your access to the Site or any purchases made through the Site; <br/>
            Exceeding or attempting to exceed quantity limits when purchasing Partner Packages or Products, or otherwise using any Perkfix account to purchase Partner Packages or Products for resale or for speculative, false, fraudulent or any other purpose not expressly permitted by these Terms of Use and the terms of a specific offer on the Site; <br/>
            Accessing, monitoring or copying any content from the Site using any “robot,” “spider,” “scraper” or other automated means or any manual process for any purpose without our express written permission; <br/>
            Violating the restrictions in any robot exclusion headers on the Site or bypassing or circumventing other measures employed to prevent or limit access to the Site; <br/>
            Aggregating any current or previously-offered deals or content or other information from the Site (whether using links or other technical means or physical records associated with purchases made through the Site) with material from other sites or on a secondary site without our express written permission; <br/>
            Deep-linking to any portion of the Site (including, without limitation, the purchase path for any Package) without our express written permission; Hyperlinking to the Site from any other website without our initial and ongoing consent; or <br/>
            Acting illegally or maliciously against the business interests or reputation of Perkfix, our Partners, or our services. <br/>
            Perkfix will have the right to cancel your account if any of the following events occur: <br/>
            The party is not using Perkfix as intended. Perkfix is a platform to offer employee perks and rewards to employees and any other use cases may go against our Terms of Service. <br/>
            The party cannot provide a valid business address within the United States. <br/>
            The party does not have a valid online reference to their business, including a valid website or online presence. <br/>
            Numerous payment cancellations and failed funding attempts within the account.</p>

            <h2>Your Privacy</h2>
            <p>We take the privacy of your personal data seriously. We encourage you to carefully review our Privacy Statement for important disclosures about ways that we may collect, use, and share personal data and your choices.</p>

            <h2>Terms of Sale and Cancellation</h2>
            <p>By adding a bank account and distributing cards to your team, you agree to these Terms of Use, including, without limitation, the Terms of Sale, available here. <br/>
            Cancellation will be handled swiftly. At time of cancellation we will freeze any cards on the account and begin the process of returning the remaining allowance amount via ACH. You will receive this remaining allowance amount within 180 days of cancellation.</p>

            <h2>Copyright and Trademarks</h2>
            <p>The Site contains copyrighted material, trademarks, and other proprietary information, including, without limitation, text, software, photos, video, graphics, music and sound, and the entire contents of the Site are protected by copyright, trademark, and other intellectual property laws of the United States. Perkfix owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. You may not modify, distribute, publish, transmit, publicly display, publicly perform, participate in the transfer or sale, create derivative works or in any way exploit any of the content, in whole or in part. Except as otherwise expressly stated under copyright law, no downloading, copying, redistribution, retransmission, publication or commercial exploitation of the content without the express permission of Perkfix or the copyright owner is permitted. If downloading, copying, redistribution, retransmission or publication of copyrighted material is permitted, you will make independent attribution and/or make no changes in or deletion of any author attribution, trademark legend or copyright notice. You acknowledge that you do not acquire any ownership rights by downloading copyrighted material. Any violation of these restrictions may result in a copyright, trademark or other intellectual property right infringement that may subject you to civil and/or criminal penalties. <br/>
            Perkfix owns trademarks, registered and unregistered, in many countries and "Perkfix," the Perkfix logos and variations thereof found on the Site are trademarks owned by Perkfix, Inc. or its related entities and all use of these marks inures to the benefit of Perkfix. <br/>
            Other marks on the site not owned by Perkfix may be under license from the trademark owner thereof, in which case such license is for the exclusive benefit and use of Perkfix unless otherwise stated, or may be the property of their respective owners. You may not use Perkfix's name, logos, trademarks or brands, or trademarks or brands of others on the Site without Perkfix's express permission.</p>

            <h2>User Content</h2>
            <p>The Site may provide registered users and visitors various opportunities to submit or post reviews, opinions, advice, ratings, discussions, comments, messages, survey responses and other communications, as well as files, images, photographs, video, sound recordings, musical works, and any other content or material submitted or posted to the Site (collectively, "User Content") through forums, bulletin boards, discussion groups, chat rooms, surveys, blogs or other communication facilities that may be offered on, through, or in connection with the Site from time to time. You may be required to have a Perkfix account to submit User Content. If you contribute any User Content, you will not upload, post or otherwise make available on the Site any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right. Perkfix does not have any express burden or responsibility to provide you with indications, markings or anything else that may aid you in determining whether the material in question is copyrighted or trademarked. You will be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights or any other harm resulting from such a submission. In addition, if you contribute any User Content, you represent and warrant that: (a) you are the creator of the User Content; or (b) if you are acting on behalf of the creator, that you have (i) express, advance authority from the creator to submit or post the User Content, and that they have waived any moral rights in such User Content, and (ii) all rights necessary to grant the licenses and grants in these Terms of Use. <br/>
            You further represent and warrant (or, if you are acting on behalf of the creator of the User Content, you have ensured that the creator represents and warrants) that the use and sharing of the User Content for the purposes you have selected will not violate or infringe any copyrights, trademarks or any other intellectual property rights or rights of third parties, including, without limitation, the rights of publicity or privacy. You represent and warrant that you will not upload, post, transmit or otherwise make available User Content that is unlawful, harmful, tortious, threatening, abusive, harassing, hateful, racist, infringing, pornographic, obscene, violent, misleading, defamatory or libelous, invasive of the privacy of another person or violative of any third-party rights; and that you will not upload, post, transmit, or otherwise make available User Content that contains any material that harbors viruses or any other computer codes, files or programs designed to interrupt, destroy or limit the functionality of any software or computer equipment. <br/>
            Perkfix shall have the sole and absolute right, but not the obligation, to review, edit, post, refuse to post, remove, monitor the User Content and disclose the User Content and the circumstances surrounding its transmission to any third-party, at any time, for any reason, including, without limitation, to determine compliance with these Terms of Use and any operating rules established by Perkfix, as well as to satisfy any applicable law, regulation or authorized government request. Without limiting the foregoing, Perkfix shall have the right to remove any material from the Communities or any other Perkfix controlled sites, in its sole discretion. Perkfix assumes no liability for any User Content or other information that appears or is removed from the Site or elsewhere. Perkfix has no obligation to use User Content and may not use it at all. <br/>
            In some instances and from time to time, it may be possible to modify or remove the User Content submitted or posted through your account. Perkfix makes no representations or warranties that the User Content you modify or remove will be modified or removed from the Site or elsewhere, or that the User Content will cease to appear on the Internet, in search engines, social media websites, or in any other form, media or technology.</p>

            <h2>Public Nature of Your User Content</h2>
            <p>You understand and agree that User Content is public. Any person (whether or not a user of Perkfix’s services) may read your User Content without your knowledge. Please do not include any Personal Information in your User Content unless you wish for it to be publicly disclosed. Perkfix is not responsible for the use or disclosure of any Personal Information that you disclose in connection with User Content. <br/>
            Any User Content of any kind made by you or any third-party is made by the respective author(s) or distributor(s) and not by Perkfix. Other users may post User Content that is inaccurate, misleading or deceptive. Perkfix does not endorse and is not responsible for any User Content, and will not be liable for any loss or damage caused by your reliance on such User Content. User Content reflects the opinions of the person submitting it and may not reflect the opinion of Perkfix. Perkfix does not control or endorse any User Content, and specifically disclaims any liability concerning or relating to your contribution of, use of, or reliance on any User Content and any actions resulting from your participation in any part of the Site, including, without limitation, any objectionable User Content.</p>

            <h2>License Grants</h2>
            <p>Some User Content you submit to Perkfix may be displayed or may give you the option to display in connection with your Personal Information, or a portion of your Personal Information, including, without limitation, but not limited to your name, initials, username, social networking website user account name, image, likeness, preferences, voice and location. You grant Perkfix a royalty-free, perpetual, irrevocable, sublicensable, fully paid-up, non-exclusive, transferrable, worldwide license and right to use, commercial use, display and distribute any Personal Information in connection with your User Content in accordance with these Terms of Use, including, without limitation, a right to offer for sale and to sell such rights in Personal Information, whether the User Content appears alone or as part of other works, and in any form, media or technology, whether now known or hereinafter developed, and to sublicense such rights through multiple tiers of sublicensees, all without compensation to you. However, Perkfix shall have no obligation to use your Personal Information in connection with any User Content. <br/>
            As between you and Perkfix, you shall retain all ownership rights in and to the User Content you submit or post. However, by contributing User Content or other information on or through the Site, you grant Perkfix a royalty-free, perpetual, irrevocable, sublicensable, fully paid-up, non-exclusive, transferrable, worldwide right and license to use, reproduce, create derivative works from, publish, edit, translate, distribute, perform, display, transmit, offer for sale and sell the User Content alone or as part of other works in any form, media or technology, whether now known or hereafter developed, and to sublicense such rights through multiple tiers of sublicensees and without compensation to you. You waive any "moral rights" or other rights with respect to attribution of authorship or integrity of materials regarding the User Content that you may have under any applicable law under any legal theory. Perkfix’s license in any User Content or Personal Information submitted includes, but is not limited to, use for promotions, advertising, marketing, market research, merchant feedback, quality control or any other lawful purpose. <br/>
            As detailed in Section 3, contributing User Content or other information on or through the Site, is limited to individuals who are over the age of majority in the state or province in which they reside. The Site is designed and intended for adults. By contributing User Content or other content on or through the Communities, you affirm that you are over the age of majority in the state or province in which they reside. We will promptly delete User Content or other content associated with any account we obtain actual knowledge of that is associated with a registered user who is not at least the age of majority in the state or province in which he or she resides. <br/>
            As detailed in Section 6, account use on behalf of a company grants Perkfix license to use that company's name and logo.</p>

            <h2>Unsolicited Ideas</h2>
            <p>YWe welcome, directly or through any Perkfix employee or agent, unsolicited ideas of any kind, particularly ideas or suggestions relating to new or improved products, enhancements, names or technologies, advertising and marketing campaigns, plans or other promotions. You may send us (or any of our employees) any unsolicited ideas, suggestions, material, images or other work in any form (“Unsolicited Materials”). If you send us Unsolicited Materials, you understand and agree that the following terms will apply, notwithstanding any cover letter or other terms that accompany them: <br/>
            Perkfix has no obligation to review any Unsolicited Materials, nor to keep any Unsolicited Materials confidential; <br/>
            and Perkfix will own, and may use and redistribute, Unsolicited Materials for any purpose without restriction and free of any obligation to acknowledge or compensate you.</p>

            <h2>Infringement Reporting Procedures and Digital Millennium Copyright Act (DMCA) Procedures</h2>
            <p>Infringement Reporting Procedures. If you own copyright, trademark, patent or other intellectual property rights (“IP Rights Owner”), or if you are an agent authorized to act on the IP Rights Owner’s behalf (“Authorized Agent”), and you have a good faith belief that material or products on the Site infringe the IP Rights Owner’s copyright, trademark, or other intellectual property right, and you would like to bring it to Perkfix's attention, you can report your concern(s) by submitting your complaint here. <br/>
            DMCA Procedures. Perkfix reserves the right to terminate your or any third-party’s right to use the Site if such use infringes the copyrights of another. Perkfix may, under appropriate circumstances and at its sole discretion, terminate your or any third-party’s right to access to the Site, if Perkfix determines that you or a third-party is a repeat infringer. If you believe that any material has been posted via the Site by any third-party in a way that constitutes copyright infringement, and you would like to bring it to Perkfix's attention, you must provide Perkfix's DMCA Agent identified below with the following information: (a) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyrighted work; (b) an identification of the copyrighted work and the location on the Site of the allegedly infringing work; (c) a written statement that you have a good faith belief that the disputed use is not authorized by the owner, its agent or the law; (d) your name and contact information, including, without limitation, telephone number and email address; and (e) a statement by you that the above information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner’s behalf. <br/>
            The contact information for Perkfix’s DMCA Agent for notice of claims of copyright infringement is: Perkfix, Inc. Attn: Copyright Agent, 135 Village Blvd, Princeton, NJ 08540, email: privacy@Perkfix.com.</p>

            <h2>Disclaimer of Warranty</h2>
            <p>YOU EXPRESSLY AGREE THAT USE OF THE SITE IS AT YOUR SOLE RISK. NONE OF Perkfix, ITS SUBSIDIARIES OR AFFILIATES OR ANY OF THEIR RESPECTIVE EMPLOYEES, AGENTS, MERCHANTS, THIRD-PARTY CONTENT PROVIDERS OR LICENSORS OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS, WARRANT THAT USE OF THE SITE WILL BE UNINTERRUPTED, SECURE, VIRUS-FREE OR ERROR FREE, NOR DO THEY MAKE ANY WARRANTY AS TO (A) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SITE, OR (B) THE ACCURACY, COMPLETENESS OR RELIABILITY OF (I) THE CONTENT ON THE SITE, INCLUDING, WITHOUT LIMITATION, PARTNER PACKAGES, PRODUCTS OR OTHER AVAILABLE PROGRAMS, (II) DESCRIPTIONS OF PARTNER PACKAGES, PRODUCTS OR OTHER AVAILABLE PROGRAMS, OR (III) USER CONTENT PROVIDED THROUGH THE SITE. THE SITE AND ALL CONTENT, USER CONTENT AND OTHER INFORMATION CONTAINED ON THE SITE, PARTNER PACKAGES, PRODUCTS AND OTHER AVAILABLE PROGRAMS ACCESSIBLE OR AVAILABLE THROUGH THE SITE, ARE MADE ACCESSIBLE OR AVAILABLE ON AN “AS IS” AND “AS AVAILABLE” BASIS. TO THE EXTENT ALLOWED BY APPLICABLE LAW, Perkfix HEREBY DISCLAIMS ANY AND ALL REPRESENTATIONS, WARRANTIES AND CONDITIONS, WHETHER EXPRESS, IMPLIED, OR STATUTORY, AS TO THE OPERATION OF THE SITE OR THE CONTENT, USER CONTENT OR OTHER INFORMATION CONTAINED ON THE SITE OR THE PARTNER PACKAGES, PRODUCTS OR OTHER AVAILABLE PROGRAMS ACCESSIBLE OR AVAILABLE THROUGH THE SITE, INCLUDING, WITHOUT LIMITATION, THOSE OF TITLE, NON-INFRINGEMENT, NON-INTERFERENCE, MERCHANTABILITY, SUITABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AS WELL AS WARRANTIES IMPLIED FROM A COURSE OF PERFORMANCE OR COURSE OF DEALING.</p>
            <h2>Limitation of Liability</h2>
            <p>IN NO EVENT SHALL Perkfix, ITS SUBSIDIARIES OR AFFILIATES OR ANY OF THEIR RESPECTIVE EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, PARTNERS, THIRD-PARTY CONTENT PROVIDERS OR LICENSORS, OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, LOST PROFIT, LOST BUSINESS, OR PUNITIVE DAMAGES ARISING OUT OF, RELATED TO, OR IN CONNECTION WITH ANY OF THE FOLLOWING: (A) YOUR USE OF THE SITE, THE CONTENT, USER CONTENT, INCLUDING, WITHOUT LIMITATION, ANY PERSONAL INFORMATION, AND ANY OTHER INFORMATION EITHER CONTAINED IN THE SITE OR SUBMITTED BY TO YOU TO THE SITE; (B) YOUR INABILITY TO USE THE SITE; (C) MODIFICATION OR REMOVAL OF CONTENT SUBMITTED ON THE SITE; (D) THE PARTNER PACKAGES, PRODUCTS AND OTHER AVAILABLE PROGRAMS ACCESSIBLE OR AVAILABLE THROUGH THE SITE; (E) ANY PRODUCTS OR SERVICES OTHER THAN PACKAGES PURCHASED OR OBTAINED FROM A PARTNER; (F) THESE TERMS OF USE; OR (G) ANY IMPROPER USE OF INFORMATION YOU PROVIDE TO THE SITE, INCLUDING, WITHOUT LIMITATION, ANY PERSONAL INFORMATION. IN NO EVENT WILL Perkfix'S LIABILITY IN CONNECTION WITH A PARTNER PACKAGE, PRODUCT, AND OTHER AVAILABLE PROGRAMS EXCEED THE AMOUNTS PAID FOR THE APPLICABLE PACKAGE, PRODUCT OR SERVICE. TOTAL AGGREGATE LIABILITY ARISING OUT OF, RELATED TO, OR IN CONNECTION WITH (A)-(G) ABOVE SHALL NOT EXCEED THE AMOUNTS PAID BY YOU DURING THE SIX MONTHS PRECEDING THE BRINGING OF ANY CLAIM. YOU AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF, RELATED TO, OR IN CONNECTION WITH (A)-(G) ABOVE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OR THE CAUSE OF ACTION IS PERMANENTLY BARRED. BECAUSE SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, ALL OR A PORTION OF THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
            <h2>Electronic Communications</h2>
            <p>When you use the Site or send emails to Perkfix, you are communicating with us electronically and consent to receive electronic communications related to your use of the Site. We will communicate with you by email or by posting notices on the Site. You agree that all agreements, notices, disclosures and other communications that are provided to you electronically satisfy any legal requirement that such communications be in writing. Notices from us will be considered delivered to you and effective when sent to the email address you provide on the Site or from which you otherwise email us.</p>
            <h2>Websites of Others</h2>
            <p>The Site contains links to websites maintained by other parties. These links are provided solely as a convenience to you and not because we endorse or have an opinion about the contents on such websites. We expressly disclaim any representations regarding the content or accuracy of materials on such websites or the privacy practices of those websites. If you decide to access websites maintained by other parties, you do so at your own risk. We are not responsible or liable, directly or indirectly, for any damage, loss or liability caused or alleged to be caused by or in connection with any use of or reliance on any content, Products or services available on or through any such linked site or resource.</p>
            <h2>Indemnification / Release</h2>
            <p>The Site contains links to websites maintained by other parties. These links are provided solely as a convenience to you and not because we endorse or have an opinion about the contents on such websites. We expressly disclaim any representations regarding the content or accuracy of materials on such websites or the privacy practices of those websites. If you decide to access websites maintained by other parties, you do so at your own risk. We are not responsible or liable, directly or indirectly, for any damage, loss or liability caused or alleged to be caused by or in connection with any use of or reliance on any content, Products or services available on or through any such linked site or resource.</p>
            <h2>Superior Force</h2>
            <p>Perkfix shall be excused from performance under these Terms of Use, to the extent it is prevented or delayed from performing, in whole or in part, as a result of an event or series of events caused by or resulting from: (a) weather conditions or other elements of nature or acts of God; (b) acts of war, acts of terrorism, insurrection, riots, civil disorders or rebellion; (c) quarantines or embargoes; (d) labor strikes; (e) error or disruption to major computer hardware or networks or software failures; or (g) other causes beyond the reasonable control of Perkfix.</p>
            <h2>Assignment</h2>
            <p>You may not assign these Terms of Use, or any rights, benefits or obligations hereunder, by operation of law or otherwise, without the express written permission of Perkfix. Any attempted assignment that does not comply with these Terms of Use shall be null and void. Perkfix may assign these Terms of Use, in whole or in part, to any third-party in its sole discretion.</p>
            <h2>Entire Agreement</h2>
            <p>The Terms of Use, including, without limitation, the incorporated Terms of Sale, Privacy Statement and other terms incorporated by reference, constitute the entire agreement and understanding between you and Perkfix with respect to the subject matter hereof and supersedes all prior or contemporaneous communications and proposals, whether oral or written, between you and Perkfix with respect to such subject matter.</p>
            <h2>Choice of Law</h2>
            <p>Any disputes arising out of or related to these Terms of Use and/or any use by you of the Site or Perkfix’s services shall be governed by the laws of the State of Illinois, without regard to its choice of law rules and without regard to conflicts of laws principles. If you reside in Canada, any disputes arising out of or related to these Terms of Use and/or any use by you of the Site or Perkfix’s services shall be governed by the laws of the Province in which you reside at the time you enter into these Terms of Use, without regard to its choice of law rules and without regard to conflicts of laws principles. <br/>
            Perkfix and you specifically disclaim the application of the United Nations Convention on Contracts for the International Sale of Goods as that Convention may be incorporated into applicable law.</p>

            <h2>Dispute Resolution</h2>
            <p>(a) Binding Arbitration. Except as specifically stated herein, any dispute or claim between you and Perkfix arising out of, relating in any way to, or in connection with the Terms of Use, the Site or your use of the Site, or any Products, Partner Packages or services offered or distributed through the Site (“Disputes”) shall be resolved exclusively by final, binding arbitration; except that you may bring a qualifying claim over a Dispute in a small claims court. By virtue of this Dispute Agreement (defined below), you and Perkfix are each giving up the right to go to court and have a Dispute heard by a judge or jury (except as otherwise set forth in this Section 24(a) or Section 24(d)). The provisions of this Section 24 shall constitute your and Perkfix’s written agreement to arbitrate Disputes under the Federal Arbitration Act (“Dispute Agreement”). Any modification to this Agreement shall be in writing and signed by you and Perkfix. The arbitration will be administered by the American Arbitration Association (“AAA”) and conducted before a single arbitrator pursuant to its rules, including, without limitation, the AAA’s Supplementary Procedures for Consumer-Related Disputes, available at http://www.adr.org or by calling 800-778-7879. The arbitrator will apply and be bound by this Agreement, apply applicable law and the facts, and issue a reasoned award. To begin an arbitration proceeding, you must comply with the limitations provision set forth in Section 24(e) and submit the Dispute by utilizing the forms available at http://www.adr.org, and simultaneously sending a copy of the completed form to the following address: Perkfix, Inc, 135 Village Blvd, Princeton, NJ 08540. Payment of all filing, administration and arbitrator fees will be governed by the AAA's rules. Perkfix will reimburse those fees for Disputes totaling less than $10,000 unless the arbitrator determines the Dispute is frivolous. Likewise, Perkfix will not seek attorneys' fees and costs in arbitration unless the arbitrator determines the Dispute is frivolous. The arbitration will be conducted based upon written submissions unless you request and/or the arbitrator determines that a telephone or in-person hearing is necessary. <br/>
            (b) No Class Action Matters. We each agree that we shall bring any Dispute against the other in our respective individual capacities and not as a plaintiff or class member in any purported class, representative proceeding or as an association. In addition, we each agree that Disputes shall be arbitrated only on an individual basis and not in a class, consolidated or representative action. The arbitrator does not have the power to vary these provisions. <br/>
            (c) Choice of Law and Forum; No Jury Trial. If for any reason a Dispute proceeds in court: (i) except with respect to a qualifying claim over a Dispute in a small claims court, you agree that any such Dispute may only be instituted in a state or federal court in Cook County, Illinois; (ii) you and Perkfix irrevocably consent and submit to the exclusive personal jurisdiction and venue of such courts for resolution of such Disputes; (iii) you and Perkfix agree that the Federal Arbitration Act, the AAA rules, applicable federal law and the laws of the State of Illinois, without regard to principles of conflicts of law, will govern this Dispute Agreement and any Disputes; and (iv) you and Perkfix agree to waive any right to a trial by jury. <br/>
            (d) Injunctive Relief. Notwithstanding anything to the contrary in this Dispute Agreement, either party may bring suit in court seeking an injunction or other equitable relief arising out of or relating to the infringement of a party’s intellectual property or any conduct that violates Section 7 (“Your Conduct”) of the Terms of Use. <br/>
            (e) Time Limitations. If either of us wants to assert a Dispute against the other, the party with a Dispute must institute arbitration within one (1) year from the date the Dispute arose. Absent commencing the arbitration within one (1) year from the date the Dispute arose, the Dispute(s) will be forever barred. <br/>
            (f) Severability. With the exception of Section 24(b) above, if any part of this Section 24 is ruled to be unenforceable, then the balance of this Section 24 shall remain in full effect and construed and enforced as if the portion ruled unenforceable were not contained herein. If Section 24(b) above is ruled to be unenforceable, then Section 24(a) shall be deemed unenforceable, but the rest of Section 24 shall remain in full effect.</p>

            <h2>Additional Disclosures</h2>
            <p>No waiver by either you or Perkfix of any breach or default or failure to exercise any right allowed under these Terms of Use is a waiver of any preceding or subsequent breach or default or a waiver or forfeiture of any similar or future rights under our Terms of Use. The section headings used herein are for convenience only and shall be of no legal force or effect. If a court of competent jurisdiction holds any provision of our Terms of Use invalid, such invalidity shall not affect the enforceability of any other provisions contained in these Terms of Use, and the remaining portions of our Terms of Use shall continue in full force and effect. <br/>
            The provisions of these Terms of Use apply equally to and are for the benefit of Perkfix, its subsidiaries, affiliates, Partners and its third-party content providers and licensors, and each shall have the right to assert and enforce such provisions directly.</p>
        </div>
    </div>
</div>
